apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contacts-pvc
  namespace: agenda-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem