name: CI/CD Rick and Morty

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: esanhuezav
          password: Wks.2011$$

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: esanhuezav/lab:${{ github.sha }}

      - name: Update manifests repo
        run: |
          git config user.name "esanhuezav"
          git config user.email "esteban.sanhueza.varas@gmail.com"
          sed -i "s|esanhuezav/lab:.*|esanhuezav/lab:${{ github.sha }}|" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
